Create_data: 
  input_size: 10
  output_size: 5
  sequence_length: 20
  num_samples: 1000
train:
  batch_size: 16
  num_epochs: 1000
  early_stopping_patience: 20
  learning_rate: 0.001
  hidden_size: 64
task: "RNN"
  